config/routes.rb
Todos::Application.routes.draw do
  root to: 'pages#show', id: 'homepage'
  resource :sessions, only: [:create, :destroy]
  resources :todos, only: [:index, :create, :update] do
    resource :completions, only: [:create, :destroy]
  end
end

app/models/guest.rb
class Guest
  def email
  end

  def todos
    []
  end

  def signed_in?
    false
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :name, :user, :completed_at

  validates :name, presence: true

  def user=(user)
    self.owner_email = user.email
  end

  def self.complete
    where('completed_at IS NOT NULL')
  end

  def self.incomplete
    where('completed_at IS NULL')
  end
end

app/models/user.rb
class User
  attr_reader :email

  def initialize(email)
    @email=email
  end

  def todos
    Todo.where(owner_email: @email)
  end

  def signed_in?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if session[:email]
      User.new(session[:email])
    else
      Guest.new
    end
  end
  helper_method :current_user

  def sign_in_user(email_address)
    session[:email] = email_address
  end

  def sign_out_user
    session[:email] = nil
  end

  def authenticate
    unless current_user.signed_in?
      redirect_to root_path, notice: 'Please sign in.'
    end
  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todo = Todo.find(params[:todo_id])
    todo.touch :completed_at
    redirect_to todos_path
  end

  def destroy
    todo = Todo.find(params[:todo_id])
    todo.update_attribute(:completed_at, nil)
    redirect_to todos_path
  end
end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController
  def show
    case params[:id]
    when 'homepage'
      if current_user.signed_in?
        redirect_to todos_path
      else
        render :homepage
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    sign_in_user params[:session][:email]
    redirect_to todos_path
  end

  def destroy
    sign_out_user
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate

  def index
    @todo = Todo.new
    @incomplete_todos = current_user.todos.incomplete
    @complete_todos = current_user.todos.complete
  end

  def create
    @todo = Todo.new(params[:todo].merge(user: current_user))

    if @todo.save
      redirect_to todos_path
    else
      @incomplete_todos = current_user.todos.incomplete
      @complete_todos = current_user.todos.complete
      render :index
    end
  end

  def update
    @todo= Todo.find params[:id]
    @todo.update_attributes(params[:todo])

    respond_to do |format|
      format.json { respond_with_bip(@todo) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todos<%= content_for?(:title) ? ' | ' : '' %><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
  </head>
  <body id="<%= yield :body_id %>">

    <%= yield :header %>

    <div class="container">
      <div class="content">
        <% flash.keys.each do |key| %>
          <%= content_tag :div, flash[key], class: "#{key} alert alert-error" %>
        <% end %>

        <%= yield %>

      </div><!--/content-->
    </div> <!-- /container -->

    <%= yield :footer %>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- Need to add New Relic -->
	 <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/todos.html.erb
<% content_for :title do %><%= current_user.email %><% end %>

<% content_for :header do %>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to 'Todos', root_path, class: 'brand' %>
        <ul class='nav pull-right'>
          <li><i class='icon-user icon-white'></i>&nbsp;<span class='navbar-text' data-current-user="<%= current_user.email %>"><%= current_user.email %></span></li>
          <li class='divider-vertical'></li>
          <li><%= link_to 'Sign out', sessions_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/application' %>

app/views/pages/homepage.html.erb
<% content_for :body_id, 'homepage' %>

<div class='hero-unit'>
  <h1 data-role='title'>Your Todos</h1>
  <p data-role='description'>Setup tasks. Get things done!</p>
  <%= form_for :session, url: sessions_path, html: {class: 'form-inline'} do |form|  %>
    <%= form.label :email, class: 'obscure' %>
    <%= form.email_field :email, placeholder: 'email@address.com', autofocus: 'autofocus' %>
    <%= form.submit 'Sign in ', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/todos/index.html.erb
<ul id='incomplete-todos' class='todo-list'>
  <% @incomplete_todos.each do |todo| %>
    <li id="<%= dom_id(todo) %>">
      <%= link_to 'complete', todo_completions_path(todo), method: :post, class: 'check complete' %>
      <%= best_in_place todo, :name %>
    </li>
  <% end %>
</ul>

<%= form_for @todo, html: {class: 'well form-inline'} do |form| %>
  <% @todo.errors.full_messages.each do |message| %>
  <div class='alert alert-error'>
    <strong>Ooops!</strong> <%= message %>
  </div>
  <% end %>
  <%= form.label :name, 'New Task', class: 'obscure' %>
  <%= form.text_field :name, autofocus: 'autofocus' %>
  <%= form.submit 'Add Task', class: 'btn btn-primary btn-large' %>
<% end %>

<ul id='complete-todos' class='todo-list'>
  <% @complete_todos.each do |todo| %>
    <li id="<%= dom_id(todo) %>">
      <%= link_to 'incomplete', todo_completions_path(todo), method: :delete, class: 'check incomplete' %>
      <%= todo.name %>
    </li>
  <% end %>
</ul>